### ISSUE TITLE
Scaling messes up the joystick

### ISSUE THREAD

**Issue by MarcoFazioRandom** [MarcoFazioRandom/Virtual-Joystick-Godot#11]
I tried many solutions to solve this issue, the problem is that the Control node has in my opinion an ugly and unreliable way to deal with position, scaling, pivot, anchors etc. So I didn't find a good way to solve this problem, if someone knows please let me know.
Personally I think Godot should update the Control node to be easier to deal with (for example give local and global variable of scale, make the pivot normalized between 0-1, etc.).
For now I'm taking a break with Godot and I don't know when I'll return to use it.

**Comment by infosisio** [comment]
I have the same problem, any help would be much appreciated.

**Comment by CarlosRios** [comment]
Did you leave for Unity? I'm thinking of doing the same actually

**Comment by MarcoFazioRandom** [comment]
I made a new version compatible with Godot 3.4 and solved the issue
