### ISSUE TITLE
how to make this joystick in 3d game?

### ISSUE THREAD

**Issue by Nikond** [MarcoFazioRandom/Virtual-Joystick-Godot#12]
please explain how I can make such a joystick in a 3d game in Godot?

**Comment by Dr-42** [comment]
Just take the output variable and hook it to whatever system you are using. For example if one joystick is for movement and another is for camera, hook the first joystick to the move_and_slide() of the player and the second to the gimbal rotations of the camera. 

The joystick is like a canvas item and will be rendered as a 2D scene on top of your 3D game scene.
