### ISSUE TITLE
Cannot disable deadzone

### ISSUE THREAD

**Issue by golddotasksquestions** [MarcoFazioRandom/Virtual-Joystick-Godot#15]
Setting the Deadzone to 0.0 will won't have the expected effect. The joystick and therefore also the KinematicBody2D will still only move after a certain threshold.

I spend some time trying to figure out why, but I did not manage to fix it.
However one thing I did notice is that the deadzone range is `export(float, 0, 0.5) var dead_zone := 0.2`
I suspected it might become an int when set to "0.0" so I changed it to `export(float, 0.0, 0.5) var dead_zone := 0.0` but that made no difference.

Would love to hear your thoughts on what to do there because this is really a fantastic Godot resource, but I can't use it in my projects with a deadzone.

**Comment by MarcoFazioRandom** [comment]
It wasn't a problem with the Deadzone, the joystick didn't start working as soon as it was touched but only after you move it a little, I fixed it simply by making the Joystick works with both InputEventScreenTouch and InputEventScreenDrag.

**Comment by golddotasksquestions** [comment]
Thank you for fixing this, it works beautifully now!
