### ISSUE TITLE
unusable, cos of weird button directions..?

### ISSUE THREAD

**Issue by samtsejerome** [MarcoFazioRandom/Virtual-Joystick-Godot#18]
just had a quick look at this to see if it'd be useful, but instead of buttons foe left, right, up and downit has buttons  diagonal directions!?
which games move in diagonals ?

**Comment by MarcoFazioRandom** [comment]
I'm sorry but I don't understand the issue, could you please be more clear on what problem did you find?
Have you read the README file and followed the instructions to use this asset correctly?

**Comment by samtsejerome** [comment]
It’s really simple, joysticks  usually go up, down, left and right, for some reason the buttons on  yours goes in diagonal directions instead ?

Jerome Mayeux

**Comment by MarcoFazioRandom** [comment]
Did you changed the "symmetry angle" variable?

**Comment by samtsejerome** [comment]
I changed no code at all, just added a print statement on pressing the joystick button(s) to see that it works  and noticed  that it’s useless to have buttons that point in diagonal directions instead of simply up down, left and  right!? 

Jerome Mayeux

**Comment by MarcoFazioRandom** [comment]
Could you show me screenshot or video? 
I can't help you if I don't know how you set up the joystick.

**Comment by samtsejerome** [comment]
Il have a look when my computer is on  sure

Jerome Mayeux
