### ISSUE TITLE
Multi-touch support not working as expected

### ISSUE THREAD

**Issue by Anthony-Kolenic** [MarcoFazioRandom/Virtual-Joystick-Godot#21]
Currently having an issue with multi touch. I have a UI with the Joystick on the left and a button to shoot on the right. If I press the shoot button before touching the joystick the button works while operating the joystick. If I operate the joystick before pressing the button initially the button fails to execute the pressed event while using the joystick.

The screen layout:
![image](https://user-images.githubusercontent.com/19734837/124148835-54ee9600-da90-11eb-867e-3a0ebeed150c.png)

The layout of the nodes:
![image](https://user-images.githubusercontent.com/19734837/124149294-bd3d7780-da90-11eb-860a-8c9649b84474.png)

Currently the joystick just prints out the angle and the button prints out fire.

**Comment by MarcoFazioRandom** [comment]
Did you solved the issue?
If not you can try the 3.4 version
