### ISSUE TITLE
Two joysticks don't work on screen 

### ISSUE THREAD

**Issue by hackerManik3** [MarcoFazioRandom/Virtual-Joystick-Godot#27]
In the test scene also you can only use only one joystick at a time...
 please fix it...

**Comment by MarcoFazioRandom** [comment]
Sorry for the bug, I'm working on it, there are multiple problems I need to solve: 

- the Project setting "emulate mouse from touch" doesn't work with multitouch.
- the gui_input function doesn't register the input when releasing the finger, it only works when InputEventScreenTouch has the property "pressed" equal to TRUE, on top of that it only works when the event is inside the Control node, so InputEventScreenDrag doesn't work well either.
- I need to use the _input function, but it doesn't work well with Control nodes.

**Comment by cesarizu** [comment]
I created a PR that works around the second problem: https://github.com/MarcoFazioRandom/Virtual-Joystick-Godot/pull/28
