### ISSUE TITLE
Improvement: working with get_vector()

### ISSUE THREAD

**Issue by heavyathan** [MarcoFazioRandom/Virtual-Joystick-Godot#31]
Your solution works great, but I wonder if is it possible to adapt joystick code to work also with Input.get_vector() as right now, only works with Input.get_axis()

Sample, in your own test.tscn:
```
	# Movement using Input functions:
	var move := Vector2.ZERO
#	move.x = Input.get_axis("ui_left", "ui_right")
#	move.y = Input.get_axis("ui_up", "ui_down")
	move = Input.get_vector("ui_left","ui_right","ui_up","ui_down") <--IT DOESN'T WORK. Joystick doesn't trigget actions
	position += move * speed * delta
```

**Comment by MarcoFazioRandom** [comment]
Made the [pull request](https://github.com/godotengine/godot/pull/58656) on Godot master branch

**Comment by kidandcat** [comment]
They accepted your PR, but you have to rebase and merge it, would you mind?

**Comment by MarcoFazioRandom** [comment]
Sadly we will have to wait for Godot devs to fix this bug.
