### ISSUE TITLE
We cannot click the buttons at the same time while using the joystick.

### ISSUE THREAD

**Issue by ismailgamedev** [MarcoFazioRandom/Virtual-Joystick-Godot#32]
We cannot click the buttons at the same time while using the joystick
![Screenshot_20220713-014835_Hunting Simuilator](https://user-images.githubusercontent.com/64804972/178617037-a7653d77-5e14-4b2d-8aa1-c03c8210807d.jpg)

**Comment by MarcoFazioRandom** [comment]
From the README: If you want multitouch, make sure to disable the option "emulate mouse from touch".

(Project -> Project Settings -> General -> Input Devices -> Emulate mouse from touch -> set to off)

**Comment by ismailgamedev** [comment]
> 

When i do that, the buttons don't work.
