### ISSUE TITLE
Update for Godot 4

### ISSUE THREAD

**Issue by donluissalcedo** [MarcoFazioRandom/Virtual-Joystick-Godot#34]
Hello, I was using your fantastic plugin in Godot 3, can you please update the code  to get it working in Godot 4 please?

There are some variable renaming and the usage of setget.

Thanks for your time and effort.

**Comment by MarcoFazioRandom** [comment]
Thank you for the kind words! 
I was waiting for the stable release of Godot 4, but I'll look into it and release a version compatibile with 4!

**Comment by pooyapower** [comment]
> Thank you for the kind words! I was waiting for the stable release of Godot 4, but I'll look into it and release a version compatibile with 4!

can you update your addon for godot 4 beta ?
thank u
