### ISSUE TITLE
Idea for a 2 stage Joystick, 2 clamp zones? 

### ISSUE THREAD

**Issue by drewdus42** [MarcoFazioRandom/Virtual-Joystick-Godot#35]
I'm thinking about controls for top down games where it's twin joysticks... so Left joystick is walk direction and if you drag outside of the first clamp zone you can trigger another action, like run... then a right joystick that is aiming and when you drag out of the first clamp zone you actually shoot.

Thoughts?

**Comment by MarcoFazioRandom** [comment]
Hello! 
Sorry for the late response... 
about your idea, keep it simple: you can just "walk" if the joystick output is < than 0.9 (try and test for a good value), "run" if it's more, same thing for the shooting action. 
The clamp zone should be used for keeping the head of joystick from going too far, not for gameplay.

PS: for walking, I personally prefer moving the character based on the output value, so it moves smoothly slow or fast based on how far I move the joystick, just like in the my test script, but you can do as you prefer :)
