### ISSUE TITLE
right stick for camera rotation

### ISSUE THREAD

**Issue by Gp-triple** [MarcoFazioRandom/Virtual-Joystick-Godot#40]
Hi, I'm tryng to use your plugin for a right stick that control 3d person camera.
the pad doesn't perform any action if i set the action "look_left" "look_right" etc for the camera rotation.
using that action with a real gamepad works fine.
any suggestions?

**Comment by MarcoFazioRandom** [comment]
Hello, 
Can you double check these: 
- is the virtual joystick's "Use Input Actions" option checked? 
- are the "Actions" on the virtual joystick options the same as the "Input Map" of the project setting?

Can you show some screenshot or code so I can better understand your issue?

**Comment by Gp-triple** [comment]
hi
the answer is yes for both the question
here's a screenshot
![image](https://user-images.githubusercontent.com/75422998/232213655-b88ce006-cb7f-4c86-be66-c70ca9137614.png)
and this is the code
`func _rotate_camera(delta: float, sens_mod: float = 1.0) -> void:
	look_dir += Input.get_vector("look_left","look_right","look_up","look_down")
	camera.rotation.y -= look_dir.x * camera_sens * sens_mod * delta
	camera.rotation.x = clamp(camera.rotation.x - look_dir.y * camera_sens * sens_mod * delta, -1.5, 1.5)
	player.rotation.y -= look_dir.x * camera_sens * sens_mod * delta
	look_dir = Vector2.ZERO`

grazie

**Comment by MarcoFazioRandom** [comment]
Hello, 
I remembered the "get_vector" is bugged, It doesn't work with simulated input. There is already a closed issue for this bug in this repo and on the Godot's repo, but the bug hasn't been fixed yet. 
 
You can use "get_axis" like in the example script.
