### ISSUE TITLE
How can I minimize the joystick 

### ISSUE THREAD

**Issue by A840w** [MarcoFazioRandom/Virtual-Joystick-Godot#41]
Pls can you give me a whole tutorial

**Comment by MarcoFazioRandom** [comment]
Hello, do you mean how to change its size, or how to do a sort of Windows' minimization reducing it to a little icon?

**Comment by A840w** [comment]
Size!!! , because its going out from the game 🥲, I tried to change the size from transform tab but its not working

**Comment by MarcoFazioRandom** [comment]
Can you show me some screenshots so I can understand better this issue: a screenshot of the screen with the joystick out of bound, a screenshot of Scene tree and one of the joystick transform tab? 
Also when you change the joystick's components size, remember to change their pivot, deadzone and clampzone.
