### ISSUE TITLE
Virtual joystick REALLY prefers diagonal movement

### ISSUE THREAD

**Issue by POtOSoftware** [MarcoFazioRandom/Virtual-Joystick-Godot#45]
Frustratingly, the only issues with my EXACT issue are closed without any solution...

Anyways, I am using this plugin on a 3D game to move the player around. The problem is that it is nearly impossible to move directly forward, backward, etc. It's doable, but once it's moved even a pixel to the left or right the player starts moving diagonally, making it super annoying to move around the game.

I have not modified the joysticks script in anyway either. If there's any way to better divide up the "input zones" that would be great.

**Comment by POtOSoftware** [comment]
I uploaded a [video](https://youtu.be/_qqqZMO8Gn0) to help try and show the issue I'm describing more clearly.

**Comment by MarcoFazioRandom** [comment]
Hello, 
I think you're referring to the issue #43, I closed it because after ~ 2 weeks I didn't get a response from the user. 
Anyway, I was already working on the fix and will commit it soon.

**Comment by POtOSoftware** [comment]
Oh wow, I actually didn't see that issue before. I copied the bit of code that issue had (except I increased 0.1 to 0.2, maybe make that value an export variable?) and it worked great.

Well anyway thanks for pointing me towards that issue! I'll be closing this one now.
