### ISSUE TITLE
 How can I minimize the joystick

### ISSUE THREAD

**Issue by 3Samourai** [MarcoFazioRandom/Virtual-Joystick-Godot#53]
The size of the joystick is too big and cover the screen
<img width="465" alt="Capture d’écran 2023-10-02 à 19 08 56" src="https://github.com/MarcoFazioRandom/Virtual-Joystick-Godot/assets/68392445/a1affb89-f3de-44ba-95e1-e612f5046239">

**Comment by MarcoFazioRandom** [comment]
Just like any other Control Node, you can scale it, or right-click on it in Scene tree and turn on "Editable Children" to change the size of the joystick.
Remember to change accordingly the deadzone and clampzone sizes.
