### ISSUE TITLE
_get_base_radius return type error

### ISSUE THREAD

**Issue by 54cz** [MarcoFazioRandom/Virtual-Joystick-Godot#59]
Error running test in version 4.2
The function should return Vector2 instead of float
![Dingtalk_20231104103117](https://github.com/MarcoFazioRandom/Virtual-Joystick-Godot/assets/22734846/5361511e-3c4e-4b0f-b5ad-3b852698f039)

**Comment by MarcoFazioRandom** [comment]
Fixed with the new commit.
