### ISSUE TITLE
Implement an export var "visibility mode" with the options: "Always" or "TouchScreen Only" like TouchScreenButton

### ISSUE THREAD

**Issue by nourthe** [MarcoFazioRandom/Virtual-Joystick-Godot#6]
It can use [this method](http://docs.godotengine.org/en/latest/classes/class_os.html#class-os-method-has-touchscreen-ui-hint) to detect if the device has a touchscreen or emulates one.

**Comment by MarcoFazioRandom** [comment]
That's a good idea! I will try to implement this.

**Comment by MarcoFazioRandom** [comment]
Done! better late than never
