### ISSUE TITLE
Incorrect input value

### ISSUE THREAD

**Issue by warent** [MarcoFazioRandom/Virtual-Joystick-Godot#60]
I found this bug which I'm pretty sure is a Godot bug rather something with this package, but I'm sharing it here for tracking purposes.

https://github.com/godotengine/godot/issues/85076

**Comment by warent** [comment]
It turns out this is a bug with the library. I've created a PR here https://github.com/MarcoFazioRandom/Virtual-Joystick-Godot/pull/62

**Comment by MarcoFazioRandom** [comment]
Fixed with #62
