### ISSUE TITLE
Bug: Flicking Joystick to opposite end too fast results in input not being released

### ISSUE THREAD

**Issue by IndieJoJo** [MarcoFazioRandom/Virtual-Joystick-Godot#63]
By flicking the joystick to the opposite end, input is not released and both ui_left and ui_right can have assigned values at the same time, resulting in slowed and other unexpected movement of character.

**Comment by IndieJoJo** [comment]
By adding this the issue is fixed

`if use_input_actions:
		if output.x > 0:
			_update_input_action(action_right, output.x)
Input.action_release(action_left)
		
else:
			_update_input_action(action_left, -output.x)
Input.action_release(action_right)
		
if output.y > 0:
			_update_input_action(action_down, output.y)
Input.action_release(action_up)
		else:
			_update_input_action(action_up, -output.y)
Input.action_release(action_down)`

**Comment by etherealxx** [comment]
I'm sure he's talking about this:
![2024-01-1217-05-46-ezgif com-video-to-gif-converter](https://github.com/MarcoFazioRandom/Virtual-Joystick-Godot/assets/64251396/41b6caad-5e8d-4fbb-807f-bb156d0d2d15)

And yes, i've tested the solution and it works.

**Comment by MarcoFazioRandom** [comment]
Fixed with #62
