### ISSUE TITLE
Não aparece o nó pra adicionar

### ISSUE THREAD

**Issue by hugofarsilva** [MarcoFazioRandom/Virtual-Joystick-Godot#66]
o seguinte erro aparece:

Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
Vulkan API 1.3.260 - Forward Mobile - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1070
 
--- Debugging process stopped ---
Remove Node(s)
  Attempt to open script 'res://joystick/virtual_joystick.gd' resulted in error 'File not found'.
  Failed loading resource: res://joystick/virtual_joystick.gd. Make sure resources have been imported by opening the project in the editor at least once.

**Comment by hugofarsilva** [comment]
Vi que é só no projeto 3d que estou fazendo... Ruim vai ser começar do zero...

**Comment by MarcoFazioRandom** [comment]
Hello, can you help me understand better? 
What are you trying to do when it gives this error? 
(I don't speak portuguese)

**Comment by hugofarsilva** [comment]
I did it... My problem was with other plugin, sorry... But i'm using yours, works well
