### ISSUE TITLE
Joystick becomes stuck

### ISSUE THREAD

**Issue by krunkske** [MarcoFazioRandom/Virtual-Joystick-Godot#68]
Well I think the video describes the issue pretty much. The screenshot is from the node structure I'm using at the moment. Sorry for the wierd video resolution OBS freaked out.

https://github.com/MarcoFazioRandom/Virtual-Joystick-Godot/assets/123201489/1ea6b804-4536-49b1-a3ac-2fadba22c59b

![image](https://github.com/MarcoFazioRandom/Virtual-Joystick-Godot/assets/123201489/2fbea4fd-3292-4ca1-ad40-560bde18ac22)

**Comment by MarcoFazioRandom** [comment]
Can you show me the joysticks' areas? It's weird that they reset to a different position from the initial one. 
Moreover, I don't recommend putting the joystick inside a box container, as it will probably modify their sizes and positions.
If you can't find a solution, can you share the scene file so I can take a look and debug it?

**Comment by krunkske** [comment]
I will send the joysticks area tomorrow. I think I left the minimum size at 100x100. For now I just harcoded the position of the joysticks based on the screen size so it's not really an issue anymore. Thanks for the response!
