### ISSUE TITLE
When using emulated touch with mouse, it is annoying that simple click and hold doesn't moves the joystick

### ISSUE THREAD

**Issue by nourthe** [MarcoFazioRandom/Virtual-Joystick-Godot#7]
In the mobile device, it is almost negligible.

**Comment by eastolfi** [comment]
Hi, I've been tinkering a few days with this repo, and you have several options as exported variables.
One of the allows you to chose the type of joystick:

> * Joystick mode:
>   * Fixed: The joystick doesn't move.
>   * Dynamic: Every time the joystick area is pressed, the joystick position is set on the touched position.
>   * Following: If the finger moves outside the joystick background, the joystick follows it.

I guess you are looking for the *Dynamic* option, maybe you can try an see if it suits you.

**Comment by nourthe** [comment]
I have to see it... I can't see it these days, but you can close the issue if you want!
Regards

**Comment by kapilmathur123** [comment]
How can i use this tool?Plz explain in brief 

Can u create youtube video on this tool?
