### ISSUE TITLE
Is there a way to use it as a simple 4 direction 80-style joypad?

### ISSUE THREAD

**Issue by coppersoft** [MarcoFazioRandom/Virtual-Joystick-Godot#71]
Ciao,

I was wondering if there is an easy way to use this component as a simple old style non analogic 4-way joystick, like it was the controller on a 1980s nintendo NES.

Something similar to what is displayed on a mobile browser when you open a pico8 game.

![9973f21c-ec11-459e-bb17-b5fb17bcdb94](https://github.com/MarcoFazioRandom/Virtual-Joystick-Godot/assets/7433095/96505c54-383e-40fd-8e1f-7dcacbfbbff6)

Thank you!

**Comment by MarcoFazioRandom** [comment]
Hello, 
for a d-pad, I would use 4 buttons over the pad sprite. The joystick's logic is too different. Maybe I can make a different node for a d-pad, but it a bit outside the scope of this project.

**Comment by coppersoft** [comment]
Okay, I understand that I am asking for something too different from the purpose of the project.
Thanks anyway!
