### ISSUE TITLE
Editor is locked when loading the project on Godot for Android

### ISSUE THREAD

**Issue by yilmazdurmaz** [MarcoFazioRandom/Virtual-Joystick-Godot#75]
I am not on PC, so I  wanted to give it a shot on the Godot editor version for Android on the phone. It is really nice to have the editor working on phone too.

I am an amateur, thus no idea how to use an addon. I downloaded this git and opened the folder in the editor.

The viewport opens with the two touch controls active, navigating the scene. But everything else in the editor seems locked up. Nothing really works except the two buttons and viewport navigation.

As you would know, the editor is also kinda a game that runs anywhere Godot can run. I think that is why the addon directly works on the viewport. So, in my opinion, this is also an issue with the addon that can lock up the games.

Please, first give advice how may I fix the issue, and check further how much it  may affect games that would use the addon

**Comment by MarcoFazioRandom** [comment]
Hello, 
I tried the same thing and got the same problem, I have two points to make:
- First of all, as this addon works on desktop, the problem has to be the editor's android version (the fact that the app gets stuck is another clue), in fact the app in still in preview so bugs are normal.
- Second, my guess is that there is a problem with the compatibility mode, try to change it to Mobile (with an editor or from desktop) and try again.

**Comment by yilmazdurmaz** [comment]
I could not make it work by editing the project file.

From a project created on android, I saw two parts to edit. 
- config/features
- rendering_method

Made them mobile. Second one did not show any effect. The first one went worse; sticks are visible and working but the viewport is just black.

**Comment by MarcoFazioRandom** [comment]
Sorry, but I'm afraid you have to wait for an update of the editor, I can't even read the error logs, as the app crashes.
 [docs.godotengine.org/en/stable/tutorials/editor/using_the_android_editor](https://docs.godotengine.org/en/stable/tutorials/editor/using_the_android_editor.html)

**Comment by yilmazdurmaz** [comment]
Since I am still not in a stable desktop environment, it is hard for me to communicate, so may I request a favor?

Can you please open an issue on the Godot's GitHub to let them know about this issue so that to make them informed?
