### ISSUE TITLE
The joystick needs multitouch support.

### ISSUE THREAD

**Issue by nourthe** [MarcoFazioRandom/Virtual-Joystick-Godot#8]
This asset is awesome, it deserves the multitouch support to be the main.

**Comment by yashtripathi** [comment]
I am an experienced web developer but new in game development I need this multi-touch support for two joysticks one for a player and another for a gun. I hope you can help

**Comment by fairhat** [comment]
@eastolfi seeing that you are currently working on implementing it, figured that might help:

I got multitouch working by just checking a "not event.is_pressed() and event.index == currentIndex"
To reset the joystick.

You don't have to actually check the global event position and if its still inside the gui rect.
The only thing you have to check in _input(event) is if the touch was released and the index of the touch is the one you registered previously. This is because releasing the touch outside the gui rect will not trigger _gui_input(e) but _input(e).

Working Example (not super clean but works):

```
var workingIndex = -1


func _input(event):
	if event is InputEventScreenTouch and not event.is_pressed() and event.index == workingIndex:
		workingIndex = -1
		_background.rect_position = _original_position
		output = Vector2.ZERO
		emit_signal("joy_release", output)
		_set_handle_center_position(_background.rect_size / 2)
		_handle.modulate = _original_color

func _gui_input(event: InputEvent) -> void:
	if event is InputEventScreenTouch and (joystick_mode == Joystick_mode.DYNAMIC or joystick_mode == Joystick_mode.FOLLOWING):
		if event.is_pressed():
			if workingIndex == -1:
				workingIndex = event.index
			if event.index == workingIndex:
				var new_pos = event.position - _background.rect_size / 2
				_background.rect_position = new_pos
		else:
			workingIndex = -1
			_background.rect_position = _original_position
			emit_signal("joy_release", Vector2.ZERO)

func _on_Background_gui_input(event: InputEvent) -> void:
	if event is InputEventScreenTouch:
		if event.is_pressed():
			_handle.modulate = _pressed_color
			workingIndex = event.index
		else:
			if event.index == workingIndex:
				is_working = false
				workingIndex = -1
				output = Vector2.ZERO
				emit_signal("joy_release", output)
				_set_handle_center_position(_background.rect_size / 2)
				_handle.modulate = _original_color
	
	if event is InputEventScreenDrag and event.index == workingIndex:
		var vector : Vector2 = event.position - _background.rect_size / 2
		var dead_size = dead_zone * _background.rect_size.x / 2
		if vector.length() < dead_size:
			is_working = false
			output = Vector2.ZERO
			emit_signal("joy_release", output)
			_set_handle_center_position(_background.rect_size / 2)
			return
		_update_output(vector)
		is_working = true
		if joystick_mode == Joystick_mode.FOLLOWING:
			_following(vector)
	elif event is InputEventScreenDrag and not event.is_pressed() and event.index == workingIndex:
		emit_signal("joy_release", Vector2.ZERO)
		workingIndex = -1
```

**Comment by fairhat** [comment]
oh also possibly worth mentioning @MarcoFazioRandom

**Comment by MarcoFazioRandom** [comment]
Sorry for the late response and thank to everyone for the great feedback!

**Comment by MarcoFazioRandom** [comment]
After debugging and many experiments I came to the conclusion that in the _gui_input() function the event InputEventScreenTouch is bugged when using the touch, because it only read the touch when is pressed but not when it's released. I will report this bug hoping it will be fixed soon.

**Comment by MarcoFazioRandom** [comment]
@nourthe @fairhat 
I finally took the time to fix the multitouch and other little bugs and to clean the code. I thank you another time to the interest you show for my project.
