### ISSUE TITLE
Godot 4.3: JoyStick Input Not Responding Correctly When Moved from Center

### ISSUE THREAD

**Issue by U29** [MarcoFazioRandom/Virtual-Joystick-Godot#80]
Hello,

I tried using the JoyStick in a test scene with Godot 4.3, but it didn't work as expected. Specifically, when I move the JoyStick from the center, the Player doesn't move. However, if I press the edge of the JoyStick, the Player does move. Additionally, if I quickly move the JoyStick outward from the center, the Player seems to move.

"Emulate Touch from Mouse": ON
"Emulate Mouse from Touch": OFF

These settings are correct, and even when I build and run it on an iPad, the behavior remains the same.

Am I doing something wrong? Or is this still an issue with Godot 4.3?

I've attached a screen capture for your review.

https://github.com/user-attachments/assets/216301e6-6da8-4153-a02a-45dfdc044667

**Comment by MarcoFazioRandom** [comment]
Can you show me the scene view with the nodes tree and the joystick selected? 
Also, did you try the Test scene included in the folder?

**Comment by U29** [comment]
Is this image okay?
![スクリーンショット 2024-08-28 9 23 20](https://github.com/user-attachments/assets/d013f9e3-881e-42b6-be70-efdceb93d445)

I’m opening a test scene included in the `virtual_joystick/test` folder.
